In [2]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[6]

np.int64(17)

In [6]:
arr[1:5]

array([12, 13, 14, 15])

In [7]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[3::2]

array([14, 16, 18, 20])

NUMPY INDEXING AND SLICING OF MATRIX

In [14]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
arr[0]

array([1, 2, 3, 4, 5])

In [16]:
arr[0][0]

np.int64(1)

In [17]:
arr[0,0]

np.int64(1)

In [ ]:
#slicig 2,3,7,8
slice=arr[0:2, 1:3]
slice

array([[2, 3],
       [7, 8]])

In [21]:
#slicing 19,20,24,25,29,30
arr[3:6, 3:6]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [22]:
#only selecting one column
arr[:, 3]

array([ 4,  9, 14, 19, 24, 29])

BOOLEAN INDEXING

In [23]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [25]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])