In [1]:
import numpy as np

ARRAY OPERATIONS

1. Arithmetic    Operations

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1
a2

array([ 6,  7,  8,  9, 10])

In [3]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [4]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [5]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1 // a2

array([0, 0, 0, 0, 0])

In [8]:
a1 ** a2


array([      1,     128,    6561,  262144, 9765625])

BROADCASTING

In [9]:
l = [10,20,20,30,40]
arr = np.array(l)

In [10]:
arr + 10

array([20, 30, 30, 40, 50])

In [11]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [13]:
arr2 * 2

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70]])

DEEP AND SHALLOW COPY

In [14]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [16]:
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [17]:
#no changes are made in original array but if there was an list 
#then the changes would have been made in original list as well 
# because of mutability of list but here we are working with array 
# which is immutable so no changes are made in original array.

# in respective of array  it is called as shallow copy
# in respective of list it is called as deep copy

a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
# this is an example of deep copy of array
a
b = a

In [19]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
# alternative for it is to use copy method of array
a
b = a.copy()
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

MATRIX OPERATIONS

In [23]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [24]:
A

array([[1, 2],
       [3, 4]])

In [25]:
B

array([[5, 6],
       [7, 8]])

In [26]:
#to multiple two matrixes

A @ B

array([[19, 22],
       [43, 50]])

In [27]:
# to multiple two matrixes we can also use dot method of array
np.dot(A,B)


array([[19, 22],
       [43, 50]])

In [28]:
# to transpose a matrix we can use T attribute of array
A.T

array([[1, 3],
       [2, 4]])

STACKING ARRAY

In [29]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])


In [30]:
np.stack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
# to stack two arrays vertically we can use vstack method of numpy
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
# to stack two arrays horizontally we can use hstack method of numpy
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
# to stack two arrays column wise we can use column_stack method of numpy
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

SPLITTING ARRAY

In [34]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# to split an array into multiple sub-arrays horizontally 
# we can use hsplit method of numpy
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [38]:
# to split an array into multiple sub-arrays vertically 
# we can use vsplit method of numpy
a = np.vsplit(c, 4)
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [40]:
#the array does not split in 1d array but 
# it splits in 2d array
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
