In [1]:
import numpy as np

ARRAY OPERATIONS

1. Arithmetic    Operations

In [3]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1
a2

array([ 6,  7,  8,  9, 10])

In [4]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [5]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [6]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1 // a2

array([0, 0, 0, 0, 0])

In [9]:
a1 ** a2


array([      1,     128,    6561,  262144, 9765625])

BROADCASTING

In [ ]:
l = [10,20,20,30,40]
arr = np.array(l)

In [11]:
arr + 10

array([20, 30, 30, 40, 50])

In [12]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
arr2 = arr2 + 10
arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

In [16]:
arr2 * 2

array([[42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70],
       [72, 74, 76, 78, 80],
       [82, 84, 86, 88, 90]])

DEEP AND SHALLOW COPY

In [32]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [21]:
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [ ]:
#no changes are made in original array but if there was an list 
#then the changes would have been made in original list as well 
# because of mutability of list but here we are working with array 
# which is immutable so no changes are made in original array.

# in respective of array  it is called as shallow copy
# in respective of list it is called as deep copy

a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# this is an example of deep copy of array
a
b = a

In [28]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
# alternative for it is to use copy method of array
a
b = a.copy()
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])