In [3]:
import numpy as np

Valid Sudoku

In [2]:
s = np.array([
[5, 3, 4, 6, 7, 8, 9, 1, 2],
[6, 7, 2, 1, 9, 5, 3, 4, 8],
[1, 9, 8, 3, 4, 2, 5, 6, 7],

[8, 5, 9, 7, 6, 1, 4, 2, 3],
[4, 2, 6, 8, 5, 3, 7, 9, 1],
[7, 1, 3, 9, 2, 4, 8, 5, 6],

[9, 6, 1, 5, 3, 7, 2, 8, 4],
[2, 8, 7, 4, 1, 9, 6, 3, 5],
[3, 4, 5, 2, 8, 6, 1, 7, 9]

])

In [ ]:
s.sum()

np.int64(405)

In [ ]:
#for rows in s:
# Sum along rows (axis=1)
b = np.sum(s, axis = 1)
b == 45
for i in b:
    if i != 45:
        print("Not a valid Sudoku")
        break
    else:    
        print("Valid Sudoku")

Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku


In [ ]:
#for columns in s:
c = np.sum(s, axis = 0)

for i in c:
    if i != 45:
        print("Not a valid Sudoku")
        break
    else:    
        print("Valid Sudoku")

Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku
Valid Sudoku


In [9]:
#for squares in s:

for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        square_sum = np.sum(s[i : i + 3, j : j + 3])
        if square_sum != 45:
            print("Not a valid Sudoku")
            break
    else:
        continue
    break
else:
    print("Valid Sudoku")

Valid Sudoku


General Questions

In [32]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
[18, 85, 78],   # Student 1
[19, 92, 88],   # Student 2
[17, 76, 95],   # Student 3
[18, 65, 70],   # Student 4
[20, 90, 85]    # Student 5
])

In [12]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [13]:
#find the average age of students.
np.mean(data[:, 0])

np.float64(18.4)

In [14]:
#Extract Math marks of all students.
data[:, 1]

array([85, 92, 76, 65, 90])

In [15]:
#Find the highest Science marks.
np.max(data[:, 2])

np.int64(95)

In [17]:
#Get details of the student who scored more than 90 in Math.
data[data[:, 1] > 90]

array([[19, 92, 88]])

In [21]:
#Increase Math marks of all students by 5.
data[:, 1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [22]:
#Find how many students are younger than 19.
np.sum(data[:, 0] < 19)

np.int64(3)

In [25]:
#Calculate the average marks in each Subject (column-wise mean).
np.mean(data[:, 1:], axis = 0)

array([86.6, 83.2])

In [28]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:, 1] >= 80) & (data[:, 2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [33]:
#Replace all Science marks < 75 with 0.
data[data[:, 2] < 75 , 2] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])